package com.offxos.launcher;

import android.app.*;import android.appwidget.*;import android.content.*;import android.content.pm.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;

/** Unified Home Edit mode: apps, folders and widgets share one persistent layout. */
public class HomeEditActivity extends Activity {
    ThemeStore theme; PerformanceStore performance; FolderStore folders; GridLayout grid; ArrayList<String> order=new ArrayList<>(); OffxWidgetHost widgetHost; AppWidgetManager widgetManager; boolean widgetsStarted=false;
    int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextColor(theme.isLight()?0xFF111318:Color.WHITE);t.setTextSize(z);t.setGravity(Gravity.CENTER);return t;}
    GradientDrawable glass(){GradientDrawable g=new GradientDrawable();g.setColor(theme.isLight()?0xCCFFFFFF:0x35FFFFFF);g.setCornerRadius(dp(24));g.setStroke(dp(1),theme.isLight()?0x55FFFFFF:0x35FFFFFF);return g;}
    @Override public void onCreate(Bundle b){super.onCreate(b);theme=new ThemeStore(this);performance=new PerformanceStore(this);folders=new FolderStore(this);widgetHost=new OffxWidgetHost(this);widgetManager=AppWidgetManager.getInstance(this);build();}
    @Override protected void onResume(){super.onResume();startWidgets();reload();} @Override protected void onPause(){stopWidgets();super.onPause();}
    void startWidgets(){if(widgetsStarted)return;try{widgetHost.startListening();widgetsStarted=true;}catch(Exception ignored){}} void stopWidgets(){if(!widgetsStarted)return;try{widgetHost.stopListening();}catch(Exception ignored){}widgetsStarted=false;}
    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(30),dp(16),dp(16));root.setBackgroundColor(theme.isLight()?0xFFF4F6FA:0xFF08090D);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView title=tv("Edit Home Screen",24);title.setTypeface(null,1);head.addView(title,new LinearLayout.LayoutParams(0,dp(52),1));TextView done=tv("Done",14);done.setBackground(glass());head.addView(done,new LinearLayout.LayoutParams(dp(78),dp(48)));root.addView(head);TextView hint=tv("Long press • drag Apps, Folders & Widgets together",12);hint.setTextColor(theme.isLight()?0x88111318:0xAAFFFFFF);root.addView(hint,new LinearLayout.LayoutParams(-1,dp(38)));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);grid=new GridLayout(this);grid.setAlignmentMode(GridLayout.ALIGN_BOUNDS);grid.setUseDefaultMargins(false);grid.setColumnCount(columns());grid.setPadding(dp(2),dp(4),dp(2),dp(18));grid.setOnDragListener((v,e)->handleDrop(e));scroll.addView(grid,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));done.setOnClickListener(v->{PremiumHomeMotion.press(v,performance.isLiteMode());v.postDelayed(this::finish,performance.isLiteMode()?70L:130L);});setContentView(root);}
    int columns(){int c=getSharedPreferences("offx_home",0).getInt("columns",4);return c<3||c>5?4:c;}
    void reload(){ArrayList<String> valid=new ArrayList<>();PackageManager pm=getPackageManager();Intent q=new Intent(Intent.ACTION_MAIN);q.addCategory(Intent.CATEGORY_LAUNCHER);for(ResolveInfo r:pm.queryIntentActivities(q,0)){if(getPackageName().equals(r.activityInfo.packageName))continue;valid.add("app:"+r.activityInfo.packageName);}for(FolderStore.Folder f:folders.getFolders())valid.add("folder:"+f.name);for(Integer id:OffxHomeWidgetStore.load(this))if(widgetManager.getAppWidgetInfo(id)!=null)valid.add("widget:"+id);order=HomeLayoutStore.sync(this,valid);render();}
    void render(){grid.removeAllViews();grid.setColumnCount(columns());int cols=columns(),width=getResources().getDisplayMetrics().widthPixels-dp(36),cell=Math.max(dp(72),width/cols),row=0,col=0;for(String key:order){if(key.startsWith("widget:")){View w=createWidget(key);GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=width;lp.height=widgetHeight(key);lp.columnSpec=GridLayout.spec(0,cols);lp.rowSpec=GridLayout.spec(row++);grid.addView(w,lp);col=0;continue;}View item=createItem(key);GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=cell;lp.height=dp(104);lp.columnSpec=GridLayout.spec(col++);lp.rowSpec=GridLayout.spec(row);grid.addView(item,lp);if(col>=cols){col=0;row++;}}}
    int widgetHeight(String key){try{int id=Integer.parseInt(key.substring(7)),s=OffxHomeWidgetLayoutStore.size(this,id);return dp(s==0?130:(s==2?186:158));}catch(Exception e){return dp(158);}}
    View createItem(String key){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(dp(4),dp(6),dp(4),dp(6));box.setBackground(glass());box.setTag(key);String label;if(key.startsWith("folder:")){TextView icon=tv("▦",30);box.addView(icon,new LinearLayout.LayoutParams(dp(52),dp(52)));label=key.substring(7);}else{String pkg=key.substring(4);ApplicationInfo ai=null;try{ai=getPackageManager().getApplicationInfo(pkg,0);}catch(Exception ignored){}if(ai!=null){ImageView iv=new ImageView(this);iv.setImageDrawable(getPackageManager().getApplicationIcon(ai));iv.setPadding(dp(3),dp(3),dp(3),dp(3));box.addView(iv,new LinearLayout.LayoutParams(dp(52),dp(52)));label=getPackageManager().getApplicationLabel(ai).toString();}else label=pkg;}TextView name=tv(label,10);name.setSingleLine();box.addView(name,new LinearLayout.LayoutParams(-1,dp(26)));attachDrag(box,key);return box;}
    View createWidget(String key){int id;try{id=Integer.parseInt(key.substring(7));}catch(Exception e){return tv("Widget",11);}AppWidgetProviderInfo info=widgetManager.getAppWidgetInfo(id);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(8),dp(8),dp(8),dp(8));card.setBackground(glass());card.setElevation(dp(8));card.setTag(key);if(info!=null)try{AppWidgetHostView view=widgetHost.createView(this,id,info);view.setPadding(dp(2),dp(2),dp(2),dp(2));card.addView(view,new LinearLayout.LayoutParams(-1,0,1));}catch(Exception ignored){}TextView label=tv("•••  Widget  •••",10);card.addView(label,new LinearLayout.LayoutParams(-1,dp(28)));attachDrag(card,key);PremiumHomeMotion.entrance(card,order.indexOf(key),performance.isLiteMode());return card;}
    void attachDrag(View v,String key){v.setOnLongClickListener(view->{ClipData data=ClipData.newPlainText("offx-home-item",key);View.DragShadowBuilder shadow=new View.DragShadowBuilder(view);boolean started=android.os.Build.VERSION.SDK_INT>=24?view.startDragAndDrop(data,shadow,view,View.DRAG_FLAG_OPAQUE):view.startDrag(data,shadow,view,0);if(started){view.setAlpha(.35f);view.setScaleX(.94f);view.setScaleY(.94f);}return true;});}
    boolean handleDrop(DragEvent e){int a=e.getAction();if(a==DragEvent.ACTION_DRAG_STARTED)return e.getClipDescription()!=null&&e.getClipDescription().hasMimeType("text/plain");if(a==DragEvent.ACTION_DRAG_ENTERED){grid.setAlpha(.94f);return true;}if(a==DragEvent.ACTION_DRAG_EXITED){grid.setAlpha(1f);return true;}if(a==DragEvent.ACTION_DROP){if(e.getClipData()==null||e.getClipData().getItemCount()==0)return false;String key=e.getClipData().getItemAt(0).getText().toString();int from=order.indexOf(key);if(from<0)return false;int target=nearestIndex(e.getX(),e.getY());order.remove(from);if(target>from)target--;target=Math.max(0,Math.min(target,order.size()));order.add(target,key);HomeLayoutStore.save(this,order);grid.setAlpha(1f);render();return true;}if(a==DragEvent.ACTION_DRAG_ENDED){grid.setAlpha(1f);for(int i=0;i<grid.getChildCount();i++){grid.getChildAt(i).setAlpha(1f);grid.getChildAt(i).setScaleX(1f);grid.getChildAt(i).setScaleY(1f);}return true;}return true;}
    int nearestIndex(float x,float y){int best=order.size();float dist=Float.MAX_VALUE;for(int i=0;i<grid.getChildCount();i++){View v=grid.getChildAt(i);float cx=v.getLeft()+v.getWidth()/2f,cy=v.getTop()+v.getHeight()/2f,d=(cx-x)*(cx-x)+(cy-y)*(cy-y);if(d<dist){dist=d;best=Math.min(i,order.size());}}return best;}
}
