package com.offxos.launcher;

import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.provider.Settings;import android.view.Gravity;import android.widget.*;

public class HomeSettingsActivity extends Activity{
 int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 ThemeStore theme; PerformanceStore performance; TextView defaultLauncher;
 TextView tv(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(z);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 GradientDrawable glass(){GradientDrawable g=new GradientDrawable();g.setColor(0x25FFFFFF);g.setCornerRadius(dp(24));g.setStroke(dp(1),0x35FFFFFF);return g;}
 void refreshDefaultLauncher(){if(defaultLauncher!=null){boolean isDefault=DefaultLauncherHelper.isDefault(this);defaultLauncher.setText(isDefault?"✓ OffxOS is Default Launcher":"Set OffxOS as Default Launcher");defaultLauncher.setContentDescription(isDefault?"OffxOS is the default launcher":"Set OffxOS as the default launcher");}}
 @Override public void onCreate(Bundle b){super.onCreate(b);theme=new ThemeStore(this);performance=new PerformanceStore(this);build();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(40),dp(18),dp(18));root.setBackgroundColor(theme.isLight()?0xFFF4F6FA:0xFF08090D);
 TextView title=tv("Home Screen",26);title.setTypeface(null,1);root.addView(title,new LinearLayout.LayoutParams(-1,dp(54)));
 TextView sub=tv("OffxOS Launcher 2.0 • Liquid Glass",13);sub.setTextColor(theme.isLight()?0x88111318:0xAAFFFFFF);root.addView(sub,new LinearLayout.LayoutParams(-1,dp(34)));
 TextView edit=tv("✦  Edit Home Screen",15);edit.setBackground(glass());edit.setPadding(dp(16),0,dp(16),0);edit.setOnClickListener(v->{PremiumHomeMotion.press(v,performance.isLiteMode());startActivity(new Intent(this,HomeEditActivity.class));});root.addView(edit,new LinearLayout.LayoutParams(-1,dp(58)));
 TextView widgets=tv("🧩  Widgets",15);widgets.setBackground(glass());widgets.setPadding(dp(16),0,dp(16),0);widgets.setOnClickListener(v->{PremiumHomeMotion.press(v,performance.isLiteMode());startActivity(new Intent(this,WidgetsActivity.class));});LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(-1,dp(58));wp.topMargin=dp(10);root.addView(widgets,wp);
 TextView wallpapers=tv("🖼  Wallpapers",15);wallpapers.setBackground(glass());wallpapers.setPadding(dp(16),0,dp(16),0);wallpapers.setOnClickListener(v->{PremiumHomeMotion.press(v,performance.isLiteMode());startActivity(new Intent(this,WallpaperActivity.class));});LinearLayout.LayoutParams wpp=new LinearLayout.LayoutParams(-1,dp(58));wpp.topMargin=dp(10);root.addView(wallpapers,wpp);
 TextView notifications=tv("🔔  Notification Access",15);notifications.setBackground(glass());notifications.setPadding(dp(16),0,dp(16),0);notifications.setOnClickListener(v->{PremiumHomeMotion.press(v,performance.isLiteMode());try{startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS));}catch(Exception e){Toast.makeText(this,"Notification settings unavailable",Toast.LENGTH_SHORT).show();}});LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-1,dp(58));np.topMargin=dp(10);root.addView(notifications,np);
 root.addView(section("Version 2.0 Features"));
 TextView features=tv("✓ Liquid Glass UI\n✓ Home edit & persistent layout\n✓ Widgets + wallpaper studio\n✓ App drawer + search\n✓ Notification center + control center\n✓ Music panel + default launcher support",13);features.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);features.setPadding(dp(16),dp(8),dp(16),dp(8));features.setBackground(glass());root.addView(features,new LinearLayout.LayoutParams(-1,dp(132)));
 root.addView(section("Grid Columns"));
 String[] cols={"3 Columns","4 Columns","5 Columns"};RadioGroup rg=new RadioGroup(this);rg.setOrientation(RadioGroup.VERTICAL);int saved=getSharedPreferences("offx_home",0).getInt("columns",4);for(String s:cols){RadioButton r=new RadioButton(this);r.setText(s);r.setTextColor(theme.isLight()?0xFF111318:Color.WHITE);r.setTextSize(15);r.setTag(Integer.parseInt(s.substring(0,1)));r.setChecked((int)r.getTag()==saved);rg.addView(r,new RadioGroup.LayoutParams(-1,dp(48)));}rg.setOnCheckedChangeListener((g,id)->{RadioButton r=g.findViewById(id);if(r!=null)getSharedPreferences("offx_home",0).edit().putInt("columns",(int)r.getTag()).apply();});root.addView(rg,new LinearLayout.LayoutParams(-1,dp(155)));
 root.addView(section("Icon Size"));SeekBar size=new SeekBar(this);size.setMax(24);size.setProgress(getSharedPreferences("offx_home",0).getInt("icon_offset",4));size.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){getSharedPreferences("offx_home",0).edit().putInt("icon_offset",p).apply();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});root.addView(size,new LinearLayout.LayoutParams(-1,dp(50)));
 TextView hint=tv("Small  •  Standard  •  Large",12);hint.setTextColor(theme.isLight()?0x88111318:0x88FFFFFF);root.addView(hint,new LinearLayout.LayoutParams(-1,dp(30)));
 TextView lite=tv(performance.isLiteMode()?"⚡ Lite Mode: ON":"⚡ Lite Mode: OFF",15);lite.setBackground(glass());lite.setPadding(dp(16),0,dp(16),0);lite.setOnClickListener(v->{performance.setLiteMode(!performance.isLiteMode());lite.setText(performance.isLiteMode()?"⚡ Lite Mode: ON":"⚡ Lite Mode: OFF");});root.addView(lite,new LinearLayout.LayoutParams(-1,dp(58)));
 root.addView(section("Default Launcher"));
 defaultLauncher=tv(DefaultLauncherHelper.isDefault(this)?"✓ OffxOS is Default Launcher":"Set OffxOS as Default Launcher",15);defaultLauncher.setBackground(glass());defaultLauncher.setPadding(dp(16),0,dp(16),0);defaultLauncher.setOnClickListener(v->{PremiumHomeMotion.press(v,performance.isLiteMode());if(DefaultLauncherHelper.isDefault(this)){Toast.makeText(this,"OffxOS is already your default launcher",Toast.LENGTH_SHORT).show();return;}if(DefaultLauncherHelper.request(this)){Toast.makeText(this,"Choose OffxOS Launcher in the system prompt",Toast.LENGTH_SHORT).show();}else{Toast.makeText(this,"Default launcher selection is unavailable on this Android version",Toast.LENGTH_SHORT).show();}});root.addView(defaultLauncher,new LinearLayout.LayoutParams(-1,dp(58)));
 TextView close=tv("Done",15);close.setGravity(Gravity.CENTER);close.setBackground(glass());close.setOnClickListener(v->{PremiumHomeMotion.press(v,performance.isLiteMode());v.postDelayed(this::finish,performance.isLiteMode()?80L:140L);});LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(58));cp.topMargin=dp(14);root.addView(close,cp);setContentView(root);}
 @Override protected void onResume(){super.onResume();refreshDefaultLauncher();}
 TextView section(String s){TextView t=tv(s,13);t.setTextColor(theme.isLight()?0x88111318:0xAAFFFFFF);t.setPadding(dp(4),dp(12),0,0);return t;}
}
