package com.offxos.launcher;

import android.app.*;import android.os.*;import android.provider.Settings;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.Drawable;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.animation.OvershootInterpolator;import android.widget.*;import android.text.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root,grid,dock; EditText search; TextView clock; ArrayList<AppInfo> apps=new ArrayList<>(); Handler handler=new Handler(Looper.getMainLooper()); boolean flashOn=false;
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    TextView tv(String s,float size){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(size);t.setGravity(Gravity.CENTER);return t;}
    GradientDrawable glass(){GradientDrawable g=new GradientDrawable();g.setColor(0x25FFFFFF);g.setCornerRadius(dp(26));g.setStroke(dp(1),0x35FFFFFF);return g;}
    GradientDrawable badgeBg(){GradientDrawable g=new GradientDrawable();g.setColor(0xFFFF2F72);g.setShape(GradientDrawable.OVAL);return g;}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.BLACK);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);build();}
    @Override protected void onResume(){super.onResume();if(grid!=null)render(search==null?"":search.getText().toString());}
    void build(){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(30),dp(16),dp(12));root.setBackgroundColor(0xFF08090D);
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);clock=tv("--:--",18);clock.setGravity(Gravity.LEFT);clock.setTypeface(null,1);info.addView(clock,new LinearLayout.LayoutParams(-1,dp(27)));TextView date=tv(new SimpleDateFormat("EEE, d MMM",Locale.getDefault()).format(new Date()),11);date.setGravity(Gravity.LEFT);date.setTextColor(0xAAFFFFFF);info.addView(date,new LinearLayout.LayoutParams(-1,dp(20)));top.addView(info,new LinearLayout.LayoutParams(0,dp(52),1));TextView logo=tv("OFFXOS",18);logo.setTypeface(null,1);logo.setBackground(glass());logo.setOnClickListener(v->startActivity(new Intent(this,LockScreenActivity.class)));top.addView(logo,new LinearLayout.LayoutParams(dp(96),dp(48)));Space sp=new Space(this);top.addView(sp,new LinearLayout.LayoutParams(dp(8),1));TextView cc=tv("☷",25);cc.setBackground(glass());cc.setOnClickListener(v->controlCenter());top.addView(cc,new LinearLayout.LayoutParams(dp(52),dp(48)));root.addView(top);
        search=new EditText(this);search.setHint("⌕  Search apps");search.setHintTextColor(0x99FFFFFF);search.setTextColor(Color.WHITE);search.setTextSize(15);search.setSingleLine();search.setPadding(dp(18),0,dp(18),0);search.setBackground(glass());root.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));
        grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);root.addView(grid,new LinearLayout.LayoutParams(-1,0,1));dock=new LinearLayout(this);dock.setGravity(Gravity.CENTER);dock.setPadding(dp(8),dp(7),dp(8),dp(7));dock.setBackground(glass());root.addView(dock,new LinearLayout.LayoutParams(-1,dp(78)));setContentView(root);loadApps();search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString());}public void afterTextChanged(Editable e){}});tick();
        root.setOnTouchListener(new View.OnTouchListener(){float downX;public boolean onTouch(View v,MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){downX=e.getX();return false;}if(e.getAction()==MotionEvent.ACTION_UP&&e.getX()-downX>140)controlCenter();return false;}});
    }
    void tick(){clock.setText(new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date()));handler.postDelayed(()->tick(),30000);}
    static class AppInfo{String label,pkg;Drawable icon;Intent intent;AppInfo(String l,String p,Drawable i,Intent x){label=l;pkg=p;icon=i;intent=x;}}
    void loadApps(){apps.clear();PackageManager pm=getPackageManager();Intent q=new Intent(Intent.ACTION_MAIN);q.addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> list=pm.queryIntentActivities(q,0);for(ResolveInfo r:list){if(getPackageName().equals(r.activityInfo.packageName))continue;Intent launch=pm.getLaunchIntentForPackage(r.activityInfo.packageName);if(launch!=null)apps.add(new AppInfo(r.loadLabel(pm).toString(),r.activityInfo.packageName,r.loadIcon(pm),launch));}Collections.sort(apps,(a,b)->a.label.compareToIgnoreCase(b.label));render("");dock.removeAllViews();for(int i=0;i<Math.min(4,apps.size());i++)addApp(dock,apps.get(i),0);}
    void render(String filter){grid.removeAllViews();ArrayList<AppInfo> shown=new ArrayList<>();String f=filter==null?"":filter.toLowerCase(Locale.getDefault());for(AppInfo a:apps)if(a.label.toLowerCase(Locale.getDefault()).contains(f))shown.add(a);int cols=4;LinearLayout row=null;for(int i=0;i<shown.size();i++){if(i%cols==0){row=new LinearLayout(this);row.setGravity(Gravity.CENTER);grid.addView(row,new LinearLayout.LayoutParams(-1,dp(94)));}addApp(row,shown.get(i),1);}}
    int badgeCount(String pkg){int c=0;for(OffxNotificationService.Notice n:OffxNotificationService.getNotices())if(pkg.equals(n.app))c++;return c;}
    void addApp(LinearLayout parent,AppInfo a,int mode){FrameLayout frame=new FrameLayout(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);ImageView iv=new ImageView(this);iv.setImageDrawable(a.icon);iv.setPadding(dp(2),dp(2),dp(2),dp(2));box.addView(iv,new LinearLayout.LayoutParams(dp(mode==0?50:52),dp(mode==0?50:52)));TextView name=tv(a.label,mode==0?9:10);name.setSingleLine();box.addView(name,new LinearLayout.LayoutParams(dp(78),dp(21)));frame.addView(box,new FrameLayout.LayoutParams(-1,-1));int count=badgeCount(a.pkg);if(count>0){TextView badge=tv(count>99?"99+":String.valueOf(count),9);badge.setTypeface(null,1);badge.setBackground(badgeBg());FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(dp(count>9?25:21),dp(21),Gravity.TOP|Gravity.RIGHT);bp.setMargins(0,dp(2),dp(5),0);frame.addView(badge,bp);}frame.setOnTouchListener(new View.OnTouchListener(){public boolean onTouch(View v,MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){v.animate().scaleX(.90f).scaleY(.90f).setDuration(90).start();return true;}if(e.getAction()==MotionEvent.ACTION_UP){v.animate().scaleX(1f).scaleY(1f).setDuration(220).setInterpolator(new OvershootInterpolator(2f)).start();try{startActivity(a.intent);}catch(Exception ignored){}return true;}if(e.getAction()==MotionEvent.ACTION_CANCEL)v.animate().scaleX(1f).scaleY(1f).setDuration(160).start();return true;}});parent.addView(frame,new LinearLayout.LayoutParams(0,-1,1));}
    void controlCenter(){final Dialog d=new Dialog(this);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(18),dp(18),dp(18),dp(18));p.setBackground(glass());TextView h=tv("OffxOS Control Center",21);h.setGravity(Gravity.LEFT);h.setTypeface(null,1);p.addView(h,new LinearLayout.LayoutParams(-1,dp(45)));LinearLayout r=new LinearLayout(this);String[] x={"Wi‑Fi","Bluetooth","Flash","Airplane"};for(String s:x){TextView b=tv(s,11);b.setBackground(glass());b.setOnClickListener(v->{if(s.equals("Flash"))toggleFlash();else if(s.equals("Wi‑Fi"))startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS));else if(s.equals("Bluetooth"))startActivity(new Intent(Settings.ACTION_BLUETOOTH_SETTINGS));else startActivity(new Intent(Settings.ACTION_AIRPLANE_MODE_SETTINGS));});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(64),1);lp.setMargins(dp(3),0,dp(3),0);r.addView(b,lp);}p.addView(r);p.addView(tv("Volume",12));android.media.AudioManager am=(android.media.AudioManager)getSystemService(AUDIO_SERVICE);SeekBar vol=new SeekBar(this);vol.setMax(am.getStreamMaxVolume(android.media.AudioManager.STREAM_MUSIC));vol.setProgress(am.getStreamVolume(android.media.AudioManager.STREAM_MUSIC));vol.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int v,boolean f){am.setStreamVolume(android.media.AudioManager.STREAM_MUSIC,v,0);}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});p.addView(vol);TextView n=tv("🔔  Notifications  •  "+OffxNotificationService.count,15);n.setGravity(Gravity.LEFT);n.setPadding(0,dp(12),0,dp(12));n.setOnClickListener(v->startActivity(new Intent(this,NotificationCenterActivity.class)));p.addView(n);TextView enable=tv("⚙  Notification Access",13);enable.setGravity(Gravity.LEFT);enable.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS)));p.addView(enable);TextView lock=tv("🔒  Lock Screen Preview",14);lock.setBackground(glass());lock.setOnClickListener(v->startActivity(new Intent(this,LockScreenActivity.class)));p.addView(lock,new LinearLayout.LayoutParams(-1,dp(54)));d.setContentView(p);d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout(-1,-2);}}
    void toggleFlash(){try{android.hardware.camera2.CameraManager cm=(android.hardware.camera2.CameraManager)getSystemService(CAMERA_SERVICE);String id=cm.getCameraIdList()[0];flashOn=!flashOn;cm.setTorchMode(id,flashOn);Toast.makeText(this,flashOn?"Flashlight ON":"Flashlight OFF",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Flashlight unavailable",Toast.LENGTH_SHORT).show();}}
}
