package com.offxos.launcher;

import android.app.*;import android.os.*;import android.provider.Settings;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.Drawable;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.animation.OvershootInterpolator;import android.widget.*;import android.text.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root,grid,dock; EditText search; TextView clock; ArrayList<AppInfo> apps=new ArrayList<>(); Handler handler=new Handler(Looper.getMainLooper()); boolean flashOn=false; FolderStore folderStore; ThemeStore themeStore; PerformanceStore performanceStore; DynamicWallpaperView wallpaper;
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    boolean light(){return themeStore!=null&&themeStore.isLight();}
    int fg(){return light()?0xFF111318:Color.WHITE;}
    int muted(){return light()?0x88111318:0xAAFFFFFF;}
    TextView tv(String s,float size){TextView t=new TextView(this);t.setText(s);t.setTextColor(fg());t.setTextSize(size);t.setGravity(Gravity.CENTER);return t;}
    GradientDrawable glass(){GradientDrawable g=new GradientDrawable();g.setColor(light()?0x66FFFFFF:0x25FFFFFF);g.setCornerRadius(dp(26));g.setStroke(dp(1),light()?0x55FFFFFF:0x35FFFFFF);return g;}
    GradientDrawable badgeBg(){GradientDrawable g=new GradientDrawable();g.setColor(0xFFFF2F72);g.setShape(GradientDrawable.OVAL);return g;}
    @Override public void onCreate(Bundle b){super.onCreate(b);themeStore=new ThemeStore(this);performanceStore=new PerformanceStore(this);folderStore=new FolderStore(this);applyBars();build();}
    void applyBars(){getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(light()?0xFFF4F5F8:Color.BLACK);int flags=View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN;if(light())flags|=View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;getWindow().getDecorView().setSystemUiVisibility(flags);}
    @Override protected void onResume(){super.onResume();if(grid!=null)render(search==null?"":search.getText().toString());}
    void build(){
        FrameLayout scene=new FrameLayout(this);wallpaper=new DynamicWallpaperView(this);wallpaper.setVisibility(performanceStore.isLiteMode()?View.INVISIBLE:View.VISIBLE);scene.addView(wallpaper,new FrameLayout.LayoutParams(-1,-1));
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(30),dp(16),dp(12));root.setBackgroundColor(light()?0x55F5F7FA:0x3308090D);scene.addView(root,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);clock=tv("--:--",18);clock.setGravity(Gravity.LEFT);clock.setTypeface(null,1);info.addView(clock,new LinearLayout.LayoutParams(-1,dp(27)));TextView date=tv(new SimpleDateFormat("EEE, d MMM",Locale.getDefault()).format(new Date()),11);date.setGravity(Gravity.LEFT);date.setTextColor(muted());info.addView(date,new LinearLayout.LayoutParams(-1,dp(20)));top.addView(info,new LinearLayout.LayoutParams(0,dp(52),1));TextView logo=tv("OFFXOS",18);logo.setTypeface(null,1);logo.setBackground(glass());logo.setOnClickListener(v->startActivity(new Intent(this,LockScreenActivity.class)));top.addView(logo,new LinearLayout.LayoutParams(dp(96),dp(48)));Space sp=new Space(this);top.addView(sp,new LinearLayout.LayoutParams(dp(8),1));TextView cc=tv("☷",25);cc.setBackground(glass());cc.setOnClickListener(v->controlCenter());top.addView(cc,new LinearLayout.LayoutParams(dp(52),dp(48)));root.addView(top);
        search=new EditText(this);search.setHint("⌕  Search apps");search.setHintTextColor(muted());search.setTextColor(fg());search.setTextSize(15);search.setSingleLine();search.setPadding(dp(18),0,dp(18),0);search.setBackground(glass());root.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));
        grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);root.addView(grid,new LinearLayout.LayoutParams(-1,0,1));dock=new LinearLayout(this);dock.setGravity(Gravity.CENTER);dock.setPadding(dp(8),dp(7),dp(8),dp(7));dock.setBackground(glass());root.addView(dock,new LinearLayout.LayoutParams(-1,dp(78)));setContentView(scene);loadApps();search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString());}public void afterTextChanged(Editable e){}});tick();root.setOnTouchListener(new View.OnTouchListener(){float downX;public boolean onTouch(View v,MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){downX=e.getX();return false;}if(e.getAction()==MotionEvent.ACTION_UP&&e.getX()-downX>140)controlCenter();return false;}});
    }
    void tick(){clock.setText(new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date()));handler.postDelayed(()->tick(),30000);}
    static class AppInfo{String label,pkg;Drawable icon;Intent intent;AppInfo(String l,String p,Drawable i,Intent x){label=l;pkg=p;icon=i;intent=x;}}
    void loadApps(){apps.clear();PackageManager pm=getPackageManager();Intent q=new Intent(Intent.ACTION_MAIN);q.addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> list=pm.queryIntentActivities(q,0);for(ResolveInfo r:list){if(getPackageName().equals(r.activityInfo.packageName))continue;Intent launch=pm.getLaunchIntentForPackage(r.activityInfo.packageName);if(launch!=null)apps.add(new AppInfo(r.loadLabel(pm).toString(),r.activityInfo.packageName,r.loadIcon(pm),launch));}Collections.sort(apps,(a,b)->a.label.compareToIgnoreCase(b.label));render("");dock.removeAllViews();for(int i=0;i<Math.min(4,apps.size());i++)addApp(dock,apps.get(i),0);}
    void render(String filter){grid.removeAllViews();String f=filter==null?"":filter.toLowerCase(Locale.getDefault());if(f.isEmpty())renderFolders();ArrayList<AppInfo> shown=new ArrayList<>();for(AppInfo a:apps)if(a.label.toLowerCase(Locale.getDefault()).contains(f)&&!isInFolder(a.pkg))shown.add(a);int cols=4;LinearLayout row=null;for(int i=0;i<shown.size();i++){if(i%cols==0){row=new LinearLayout(this);row.setGravity(Gravity.CENTER);grid.addView(row,new LinearLayout.LayoutParams(-1,dp(94)));}addApp(row,shown.get(i),1);}}
    boolean isInFolder(String pkg){for(FolderStore.Folder f:folderStore.getFolders())if(f.packages.contains(pkg))return true;return false;}
    void renderFolders(){ArrayList<FolderStore.Folder> fs=folderStore.getFolders();if(fs.isEmpty())return;TextView title=tv("Folders",13);title.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);title.setTextColor(muted());grid.addView(title,new LinearLayout.LayoutParams(-1,dp(30)));LinearLayout row=null;for(int i=0;i<fs.size();i++){if(i%4==0){row=new LinearLayout(this);row.setGravity(Gravity.CENTER);grid.addView(row,new LinearLayout.LayoutParams(-1,dp(94)));}addFolder(row,fs.get(i));}}
    void addFolder(LinearLayout parent,FolderStore.Folder f){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);TextView icon=tv("▦",29);icon.setBackground(glass());box.addView(icon,new LinearLayout.LayoutParams(dp(54),dp(54)));TextView name=tv(f.name,10);name.setSingleLine();box.addView(name,new LinearLayout.LayoutParams(dp(78),dp(22)));box.setOnClickListener(v->openFolder(f.name));parent.addView(box,new LinearLayout.LayoutParams(0,-1,1));}
    int badgeCount(String pkg){int c=0;for(OffxNotificationService.Notice n:OffxNotificationService.getNotices())if(pkg.equals(n.app))c++;return c;}
    AppInfo findApp(String pkg){for(AppInfo a:apps)if(a.pkg.equals(pkg))return a;return null;}
    void addApp(LinearLayout parent,AppInfo a,int mode){FrameLayout frame=new FrameLayout(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);ImageView iv=new ImageView(this);iv.setImageDrawable(a.icon);iv.setPadding(dp(2),dp(2),dp(2),dp(2));box.addView(iv,new LinearLayout.LayoutParams(dp(mode==0?50:52),dp(mode==0?50:52)));TextView name=tv(a.label,mode==0?9:10);name.setSingleLine();box.addView(name,new LinearLayout.LayoutParams(dp(78),dp(21)));frame.addView(box,new FrameLayout.LayoutParams(-1,-1));int count=badgeCount(a.pkg);if(count>0){TextView badge=tv(count>99?"99+":String.valueOf(count),9);badge.setTypeface(null,1);badge.setBackground(badgeBg());FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(dp(count>9?25:21),dp(21),Gravity.TOP|Gravity.RIGHT);bp.setMargins(0,dp(2),dp(5),0);frame.addView(badge,bp);}frame.setOnClickListener(v->{v.animate().scaleX(.90f).scaleY(.90f).setDuration(80).withEndAction(()->{v.animate().scaleX(1f).scaleY(1f).setDuration(230).setInterpolator(new OvershootInterpolator(2f)).start();try{startActivity(a.intent);}catch(Exception ignored){}}).start();});frame.setOnLongClickListener(v->{appActions(a);return true;});parent.addView(frame,new LinearLayout.LayoutParams(0,-1,1));}
    void appActions(AppInfo a){new AlertDialog.Builder(this).setTitle(a.label).setItems(new String[]{"Open","Add to Folder","Create New Folder"},(d,which)->{if(which==0)startActivity(a.intent);else if(which==1)addToFolderDialog(a);else createFolderDialog(a);}).show();}
    void createFolderDialog(AppInfo first){final EditText input=new EditText(this);input.setHint("Folder name");input.setSingleLine();LinearLayout wrap=new LinearLayout(this);wrap.setPadding(dp(24),0,dp(24),0);wrap.addView(input,new LinearLayout.LayoutParams(-1,dp(55)));new AlertDialog.Builder(this).setTitle("Create Folder").setView(wrap).setPositiveButton("Create",(d,w)->{String n=input.getText().toString().trim();if(folderStore.create(n)){folderStore.addToFolder(n,first.pkg);render(search.getText().toString());Toast.makeText(this,"Folder created",Toast.LENGTH_SHORT).show();}else Toast.makeText(this,"Folder name already exists",Toast.LENGTH_SHORT).show();}).setNegativeButton("Cancel",null).show();}
    void addToFolderDialog(AppInfo a){ArrayList<FolderStore.Folder> fs=folderStore.getFolders();if(fs.isEmpty()){createFolderDialog(a);return;}String[] names=new String[fs.size()];for(int i=0;i<fs.size();i++)names[i]=fs.get(i).name;new AlertDialog.Builder(this).setTitle("Add to Folder").setItems(names,(d,w)->{folderStore.addToFolder(names[w],a.pkg);render(search.getText().toString());Toast.makeText(this,"Added to "+names[w],Toast.LENGTH_SHORT).show();}).setNegativeButton("Cancel",null).show();}
    void openFolder(String name){FolderStore.Folder target=null;for(FolderStore.Folder f:folderStore.getFolders())if(f.name.equals(name))target=f;if(target==null)return;LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(18),dp(14),dp(18),dp(10));p.setBackground(glass());TextView h=tv(name,20);h.setGravity(Gravity.LEFT);h.setTypeface(null,1);p.addView(h,new LinearLayout.LayoutParams(-1,dp(42)));LinearLayout row=null;int shown=0;for(String pkg:target.packages){AppInfo a=findApp(pkg);if(a==null)continue;if(shown%4==0){row=new LinearLayout(this);row.setGravity(Gravity.CENTER);p.addView(row,new LinearLayout.LayoutParams(-1,dp(92)));}addApp(row,a,1);shown++;}if(shown==0){TextView empty=tv("Folder is empty",13);p.addView(empty,new LinearLayout.LayoutParams(-1,dp(60)));}new AlertDialog.Builder(this).setView(p).setPositiveButton("Done",null).setNeutralButton("Add Apps",(d,w)->chooseAppsForFolder(name)).show();}
    void chooseAppsForFolder(String name){ArrayList<AppInfo> available=new ArrayList<>();for(AppInfo a:apps)if(!isInFolder(a.pkg))available.add(a);if(available.isEmpty()){Toast.makeText(this,"No apps available",Toast.LENGTH_SHORT).show();return;}String[] labels=new String[available.size()];boolean[] checked=new boolean[available.size()];for(int i=0;i<available.size();i++)labels[i]=available.get(i).label;new AlertDialog.Builder(this).setTitle("Add Apps").setMultiChoiceItems(labels,checked,(d,w,c)->checked[w]=c).setPositiveButton("Add",(d,w)->{for(int i=0;i<available.size();i++)if(checked[i])folderStore.addToFolder(name,available.get(i).pkg);render(search.getText().toString());}).setNegativeButton("Cancel",null).show();}
    void controlCenter(){final Dialog d=new Dialog(this);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(18),dp(18),dp(18),dp(18));p.setBackground(glass());TextView h=tv("OffxOS Control Center",21);h.setGravity(Gravity.LEFT);h.setTypeface(null,1);p.addView(h,new LinearLayout.LayoutParams(-1,dp(45)));LinearLayout r=new LinearLayout(this);String[] x={"Wi‑Fi","Bluetooth","Flash","Airplane"};for(String s:x){TextView b=tv(s,11);b.setBackground(glass());b.setOnClickListener(v->{if(s.equals("Flash"))toggleFlash();else if(s.equals("Wi‑Fi"))startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS));else if(s.equals("Bluetooth"))startActivity(new Intent(Settings.ACTION_BLUETOOTH_SETTINGS));else startActivity(new Intent(Settings.ACTION_AIRPLANE_MODE_SETTINGS));});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(64),1);lp.setMargins(dp(3),0,dp(3),0);r.addView(b,lp);}p.addView(r);p.addView(tv("Volume",12));android.media.AudioManager am=(android.media.AudioManager)getSystemService(AUDIO_SERVICE);SeekBar vol=new SeekBar(this);vol.setMax(am.getStreamMaxVolume(android.media.AudioManager.STREAM_MUSIC));vol.setProgress(am.getStreamVolume(android.media.AudioManager.STREAM_MUSIC));vol.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int v,boolean f){am.setStreamVolume(android.media.AudioManager.STREAM_MUSIC,v,0);}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});p.addView(vol);TextView theme=tv(light()?"☀  Light Theme":"☾  Dark Theme",14);theme.setGravity(Gravity.LEFT);theme.setPadding(0,dp(10),0,dp(10));theme.setOnClickListener(v->{themeStore.setLight(!light());d.dismiss();applyBars();build();});p.addView(theme);TextView lite=tv(performanceStore.isLiteMode()?"⚡  Lite Mode ON":"⚡  Lite Mode OFF",14);lite.setGravity(Gravity.LEFT);lite.setPadding(0,dp(10),0,dp(10));lite.setOnClickListener(v->{performanceStore.setLiteMode(!performanceStore.isLiteMode());d.dismiss();build();});p.addView(lite);TextView n=tv("🔔  Notifications  •  "+OffxNotificationService.count,15);n.setGravity(Gravity.LEFT);n.setPadding(0,dp(12),0,dp(12));n.setOnClickListener(v->startActivity(new Intent(this,NotificationCenterActivity.class)));p.addView(n);TextView enable=tv("⚙  Notification Access",13);enable.setGravity(Gravity.LEFT);enable.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS)));p.addView(enable);TextView lock=tv("🔒  Lock Screen Preview",14);lock.setBackground(glass());lock.setOnClickListener(v->startActivity(new Intent(this,LockScreenActivity.class)));p.addView(lock,new LinearLayout.LayoutParams(-1,dp(54)));d.setContentView(p);d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout(-1,-2);}}
    void toggleFlash(){try{android.hardware.camera2.CameraManager cm=(android.hardware.camera2.CameraManager)getSystemService(CAMERA_SERVICE);String id=cm.getCameraIdList()[0];flashOn=!flashOn;cm.setTorchMode(id,flashOn);Toast.makeText(this,flashOn?"Flashlight ON":"Flashlight OFF",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Flashlight unavailable",Toast.LENGTH_SHORT).show();}}
}
